### YamlMime:Role 
title: Ingenieros de datos 
metadata: 
  title: Ingenieros de datos  
  description: Los ingenieros de datos diseñan e implementan la gestión, el monitoreo, la seguridad y la privacidad de los datos utilizando la pila completa de servicios de datos.
uid: role.data-engineer 
summary: | 
  Los ingenieros de datos diseñan e implementan la gestión, el monitoreo, la seguridad y la privacidad de los datos utilizando la pila completa de servicios de datos.
subTitle: Los ingenieros de datos diseñan e implementan la gestión, el monitoreo, la seguridad y la privacidad de los datos utilizando la pila completa de servicios de datos.
certificationPaths: 
- title: Azure Data Engineer
  linkedInKeywords: Azure Data Engineer
  uid: certification-path.azure-data-engineer 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-data-engineer
    levels:
    - intermediate  
certifications:
- uid: certification.azure-data-engineer
  requiredExams:
  - uid: exam.dp-200
  - uid: exam.dp-201
resources:
- title: Guía de formación y certificaciones de Microsoft
  description: Explore todas las certificaciones en una guía concisa de capacitación y certificaciones.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: Póster de formación y certificaciones
  description: Elija su ruta hacia el éxito con este póster de capacitación y certificaciones.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Soporte para certificaciones
  href: ../help.md
  description: Obtener ayuda mediante Foros de soporte técnico de Certificación Un moderador del foro responderá en un día hábil, de lunes a viernes.
