### YamlMime:Role 
title: Desarrollador 
metadata: 
  title: Desarrollador 
  description: Los desarrolladores de diseñan, construyen, prueban y mantienen soluciones. Los desarrolladores implementan aplicaciones y servicios al asociarse con Solution Architects y clientes.
uid: role.developer 
summary: | 
  Los desarrolladores de diseñan, construyen, prueban y mantienen soluciones. Los desarrolladores implementan aplicaciones y servicios al asociarse con Solution Architects y clientes.
subTitle: Los desarrolladores de diseñan, construyen, prueban y mantienen soluciones en la nube.
certificationPaths: 
- title: Desarrollador Azure
  linkedInKeywords: Desarrollador Azure
  uid: certification-path.developer 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-developer
    levels:
    - intermediate 
- title: Dynamics 365 Finance and Operations Apps Developer
  linkedInKeywords: Dynamics 365 Finance and Operations Apps Developer
  uid: certification.d365-finance-and-operations-apps-developer-associate
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-finance-and-operations-apps-developer-associate
    levels:
    - intermediate 
- title: Microsoft 365 Developer
  linkedInKeywords: Microsoft 365 Developer
  uid: certification.m365-developer-associate
  prerequisites: 
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.m365-developer-associate
    levels:
    - intermediate 
- title: Power Apps + Dynamics 365 Developer
  linkedInKeywords: Power Apps + Dynamics 365 Developer
  uid: certification.power-apps-and-d365-developer-associate
  prerequisites: 
  - uid: certification.power-platform-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.power-apps-and-d365-developer-associate
    levels:
    - intermediate 
certifications:
- uid: certification.azure-developer
  requiredExams:
  - uid: exam.az-203
- uid: certification.d365-finance-and-operations-apps-developer-associate
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-500
- uid: certification.m365-developer-associate
  requiredExams:
  - uid: exam.ms-600
- uid: certification.power-apps-and-d365-developer-associate
  requiredExams:
  - uid: exam.pl-900
resources:
- title: Guía de formación y certificaciones de Microsoft
  description: Explore todas las certificaciones en una guía concisa de capacitación y certificaciones.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: Póster de formación y certificaciones
  description: Elija su ruta hacia el éxito con este póster de capacitación y certificaciones.
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Soporte para certificaciones
  href: ../help.md
  description: Obtener ayuda mediante Foros de soporte técnico de Certificación Un moderador del foro responderá en un día hábil, de lunes a viernes.
