### YamlMime:Role 
title: Functional Consultant 
metadata: 
  title: Functional Consultant 
  description: Los consultores funcionales aprovechan Microsoft Dynamics 365 y Microsoft Power Platform para anticipar y planificar las necesidades del cliente. 
uid: role.functional-consultant 
summary: | 
  Los consultores funcionales aprovechan Microsoft Dynamics 365 y Microsoft Power Platform para anticipar y planificar las necesidades del cliente.
subTitle: Los consultores funcionales aprovechan Microsoft Dynamics 365 y Microsoft Power Platform para anticipar y planificar las necesidades del cliente.
certificationPaths: 
- title: Dynamics 365 Customer Service Functional Consultant
  linkedInKeywords: Dynamics 365 Customer Service Functional Consultant
  uid: certification-path.d365-functional-consultant-customer-service 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-customer-service
    levels:
    - intermediate
    
- title: Dynamics 365 Field Service Functional Consultant
  linkedInKeywords: Dynamics 365 Field Service Functional Consultant
  uid: certification-path.d365-functional-consultant-field-service 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-field-service
    levels:
    - intermediate

- title: Dynamics 365 Finance Functional Consultant
  linkedInKeywords: Dynamics 365 Finance Functional Consultant
  uid: certification-path.d365-functional-consultant-financials 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-financials
    levels:
    - intermediate

- title: Dynamics 365 Manufacturing Functional Consultant
  linkedInKeywords: Dynamics 365 Manufacturing Functional Consultant
  uid: certification-path.d365-functional-consultant-manufacturing
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-manufacturing
    levels:
    - intermediate

- title: Dynamics 365 Marketing Functional Consultant
  linkedInKeywords: Dynamics 365 Marketing Functional Consultant
  uid: certification-path.d365-functional-consultant-marketing 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-marketing
    levels:
    - intermediate

- title: Dynamics 365 Sales Functional Consultant
  linkedInKeywords: Dynamics 365 Sales Functional Consultant
  uid: certification-path.d365-functional-consultant-sales 
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-sales
    levels:
    - intermediate

- title: Dynamics 365 Supply Chain Management Functional Consultant
  linkedInKeywords: Dynamics 365 Supply Chain Management Functional Consultant
  uid: certification-path.d365-functional-consultant-supply-chain-management
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-functional-consultant-supply-chain-management
    levels:
    - intermediate

- title: Power Platform Functional Consultant
  linkedInKeywords: Power Platform Functional Consultant
  uid: certification-path.power-platform-functional-consultant-associate
  prerequisites: 
  - uid: certification.power-platform-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.power-platform-functional-consultant-associate
    levels:
    - intermediate

- title: Dynamics 365 Business Central Functional Consultant
  linkedInKeywords: Dynamics 365 Business Central Functional Consultant
  uid: certification-path.d365-business-central-functional-consultant-associate
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.d365-business-central-functional-consultant-associate
    levels:
    - intermediate

certifications:
- uid: certification.d365-functional-consultant-customer-service
  requiredExams:
  - uid: exam.pl-200
  - uid: exam.mb-230  

- uid: certification.d365-functional-consultant-field-service
  requiredExams:
  - uid: exam.pl-200
  - uid: exam.mb-240

- uid: certification.d365-functional-consultant-financials
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-310  

- uid: certification.d365-functional-consultant-manufacturing
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-320  

- uid: certification.d365-functional-consultant-marketing
  requiredExams:
  - uid: exam.pl-200
  - uid: exam.mb-220  

- uid: certification.d365-functional-consultant-sales
  requiredExams:
  - uid: exam.pl-200
  - uid: exam.mb-210  

- uid: certification.d365-functional-consultant-supply-chain-management
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-330  
- uid: certification.power-platform-functional-consultant-associate
  requiredExams:
  - uid: exam.pl-200  
- uid: certification.d365-business-central-functional-consultant-associate
  requiredExams:
  - uid: exam.mb-800
resources:
- title: Guía de formación y certificaciones de Microsoft
  description: Estudie todas las certificaciones en una guía concisa de formación y certificaciones.
  href: https://aka.ms/TrainingCertDeck
- title: Póster de formación y certificaciones
  description: Elija su ruta hacia el éxito con este póster de capacitación y certificaciones.
  href: https://aka.ms/traincertposter
- title: Soporte para certificaciones
  href: ../help.md
  description: Obtener ayuda mediante Foros de soporte de Microsoft Certification. Un moderador de foro responderá en el trascurso de un día hábil, de lunes a viernes.
